#!/usr/bin/env python3
"""
tasks_md_sweep.py - every 10 min. Reads ~/vault/tasks.md, finds checked
boxes (`- [x]` lines with `^tID` block reference), closes those tasks in
db.sqlite. Then re-renders tasks.md from db (so file stays in sync).

This makes Obsidian-side tickoffs flow back into the task system.

Cron: */10 * * * * /usr/bin/python3 /path/to/ai-ops-agent/scripts/tasks_md_sweep.py >> /tmp/tasks_md_sweep.log 2>&1
"""
import os
import re
import sqlite3
from datetime import date
from pathlib import Path

HOME = Path.home()
VAULT = Path(os.environ.get("AGENT_VAULT_DIR", str(Path.home() / "vault"))).expanduser()
TASKS_MD = VAULT / "tasks.md"
DB_PATH = VAULT / "db.sqlite"

CHECKED_RE = re.compile(r"^\s*-\s*\[x\]\s+(.+?)\s*\^t(\d+)\s*$", re.IGNORECASE)


def render_tasks_md(conn) -> tuple[int, int]:
    """Regenerate tasks.md from db. Mirrors agent_mcp.py:_render_tasks_md."""
    open_rows = conn.execute(
        "SELECT id, text, priority, created_at FROM tasks WHERE status='open' "
        "ORDER BY CASE priority WHEN 'high' THEN 0 WHEN 'normal' THEN 1 ELSE 2 END, created_at DESC"
    ).fetchall()
    today = date.today().isoformat()
    done_today = conn.execute(
        "SELECT id, text, done_at FROM tasks WHERE status='done' AND date(done_at)=? "
        "ORDER BY done_at DESC",
        (today,),
    ).fetchall()
    lines = [
        "# Tasks",
        "",
        "_Auto-generated by the agent from db.sqlite. Tick `[x]` to close (synced back every 10 min)._",
        "",
    ]
    if open_rows:
        lines.append("## Open")
        lines.append("")
        for r in open_rows:
            prio_icon = {"high": " 🔼", "low": " 🔽"}.get(r["priority"], "")
            lines.append(f"- [ ] {r['text']}{prio_icon}  ^t{r['id']}")
        lines.append("")
    if done_today:
        lines.append(f"## Done today ({today})")
        lines.append("")
        for r in done_today:
            lines.append(f"- [x] {r['text']}  ^t{r['id']}")
        lines.append("")
    if not open_rows and not done_today:
        lines.append("_No tasks yet._")
        lines.append("")
    TASKS_MD.write_text("\n".join(lines))
    return len(open_rows), len(done_today)


def main():
    if not TASKS_MD.exists():
        print("[skip] no tasks.md")
        return
    if not DB_PATH.exists():
        print("[skip] no db")
        return
    text = TASKS_MD.read_text()
    to_close = []
    for line in text.splitlines():
        m = CHECKED_RE.match(line)
        if m:
            to_close.append(int(m.group(2)))
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    closed = 0
    for tid in to_close:
        cur = conn.execute(
            "UPDATE tasks SET status='done', done_at=datetime('now') "
            "WHERE id=? AND status='open'",
            (tid,),
        )
        if cur.rowcount:
            closed += 1
    conn.commit()
    open_n, done_n = render_tasks_md(conn)
    conn.close()
    print(f"[done] closed={closed}/{len(to_close)} ticks  open={open_n}  done_today={done_n}")


if __name__ == "__main__":
    main()
